version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:80"

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb